apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-server
    app.kubernetes.io/part-of: app-3
  name: simple-server
  namespace: gbenhaim
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: simple-server
    weight: 100
status: {}
