apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-server
    app.kubernetes.io/part-of: app-3
  name: simple-server
  namespace: gbenhaim
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: simple-server
status:
  loadBalancer: {}
