apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: simple-server
  namespace: gbenhaim
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: app-3
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: simple-server
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: simple-server-
      labels:
        build.appstudio.openshift.io/application: app-3
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: simple-server
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: gbenhaim
    spec:
      params:
      - name: git-url
        value: https://github.com/gbenhaim/demo-go-app
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:gbenhaim-simple-server-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:3dddea8074c9fa13e7146e3c5c7d75e4bd8f7bb0
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: simple-server/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
